#tempo de espera para começar o programa após inicio
tempo_comecar_programa: 5
#quantidade de scrolls a se fazer (aumente ou diminua de acordo com a quantidade de naves que possui - 10 scrolls servem pra 40 naves)
qtd_scrolls: 10
#tempo de espera a cada clique
tempo_clique: 1
#tamanho do scroll
click_and_drag_amount: 200
#qtd monitores ativos
qtd_monitores: 1
#grau de confianca para o click no botao fight (quanto mais perto de 1 mais preciso de acordo com a imagem salva - mude isso se não estiver saindo do botão de fight ou se não tiver selecionando) 
confianca_botao_fight: 0.92
#grau de confianca para detecção de se todas as naves ja foram selecionadas (mude isso se não estiver clicando pra entrar no boss)
confianca_naves_selecionadas: 0.96
#grau de confianca para detecção de quando as naves já quebraram (mude isso para menor caso não esteja saindo da tela de batalha)
confianca_naves_quebradas: 0.89
#grau de confianca no boss que for dar surrender (mude isso caso não esteja dando surrender ao chegar no boss selecionado abaixo)
confianca_boss_label: 0.95
#define em qual boss dar surrender (maximo 11, qualquer numero maior que isso vai dar erro)
parar_no_boss: 11
# define um tempo de intervalo para realizar o refresh de pagina (se ficar aberto por muito tempo acaba bugando o jogo)
atualizar_pagina_em_segundos: 4200